// ============================================================
// VIDA FORTE — Versão Aprimorada (Parte 1/3)
// Arquitetura: Separação de UI, Lógica e Persistência
// Offline-first com persistência local (localStorage)
// Design original mantido 100%
// ============================================================

import React, { useState, useEffect, useCallback, useRef, createContext, useContext, memo } from "react";
import {
  ArrowLeft, ArrowRight, Home, ListChecks, BarChart3, Users, User, Bell, Flame,
  Droplet, Dumbbell, Utensils, BookOpen, Moon, Brain, Check, Target, Mic, MicOff,
  Phone, PhoneOff, Send, Sparkles, Camera, Fingerprint, Heart, Globe, TrendingUp,
  ChevronDown, ChevronRight, RefreshCw, Trophy, MessageCircle, Type, Settings,
  Award, Crown, Infinity as InfinityIcon, Cloud, BarChart2, FileText, Rocket,
  Watch, Video, Lock, Shield, Pin, Volume2, VolumeX, Moon as MoonIcon,
  Sun, WifiOff, AlertTriangle, CheckCircle2, X, Eye, EyeOff, Mail, LogIn,
  UserPlus, Trash2, Download, Upload, Languages, Star, HelpCircle, FileQuestion,
  Zap, Activity, Calendar, Clock, Map, ChevronUp, Share2, ThumbsUp, MessageSquare,
  Edit3, Save, RotateCcw, Play, Pause, SkipForward, SkipBack, Info, Smartphone,
  KeyRound, Database, Globe2, FileCheck, HandHeart
} from "lucide-react";
import { LineChart, Line, ResponsiveContainer, XAxis, YAxis } from "recharts";
import './index.css';

// ============================================================
// CONSTANTES E CONFIGURACOES
// ============================================================

const GREEN = "#39FF6A";
const GREEN_DARK = "#166534";
const BG = "#050806";
const CARD = "#0E1410";
const BORDER = "#1E2A22";
const MUTED = "#8FA69A";
const DIM = "#5C6E64";
const ERROR = "#E5484D";
const WARNING = "#F59E0B";

const APP_VERSION = "1.0.0";
const APP_BUILD_DATE = "08/07/2026";
const SUPPORT_PHONE = "+55 47 99713-8078";
const SUPPORT_EMAIL = "vidaforteprofissional@gmail.com";

const STORAGE_KEYS = {
  USER: "vf_user",
  HABITS: "vf_habits",
  SETTINGS: "vf_settings",
  XP: "vf_xp",
  STREAK: "vf_streak",
  MAX_STREAK: "vf_max_streak",
  ACHIEVEMENTS: "vf_achievements",
  MEALS: "vf_meals",
  MESSAGES: "vf_messages",
  DAILY_MISSIONS: "vf_daily_missions",
  LAST_OPEN_DATE: "vf_last_open_date",
  FIRST_LAUNCH: "vf_first_launch",
  STATS_HISTORY: "vf_stats_history",
  BACKUP: "vf_backup",
};

const LANGUAGES = {
  pt: {
    name: "Portugues",
    welcome: "Bem-vindo",
    habits: "Habitos",
    stats: "Estatisticas",
    community: "Comunidade",
    profile: "Perfil",
    settings: "Configuracoes",
    logout: "Sair",
    save: "Salvar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Excluir",
    confirm: "Confirmar",
    back: "Voltar",
    next: "Proximo",
    done: "Concluir",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    offline: "Sem conexao",
    retry: "Tentar novamente",
    water: "Agua",
    sleep: "Sono",
    workout: "Treino",
    reading: "Leitura",
    meditation: "Meditacao",
    nutrition: "Alimentacao",
    streak: "Sequencia",
    level: "Nivel",
    xp: "XP",
    dailyMission: "Missao do Dia",
    coach: "Dra. Helena",
    manifesto: "Manifesto Vida Forte",
    about: "Sobre",
    privacy: "Privacidade",
    terms: "Termos de Uso",
    support: "Suporte",
    share: "Compartilhar",
    rate: "Avaliar",
    suggest: "Enviar sugestao",
    report: "Reportar problema",
    contact: "Fale conosco",
    version: "Versao",
    changelog: "Novidades",
    thankYou: "Obrigado por fazer parte do VIDA FORTE. Cada habito concluido e um passo em direcao a sua melhor versao. Continue evoluindo.",
    manifestoText: "Acreditamos que grandes transformacoes nao acontecem em um unico dia. Elas sao construidas por pequenas escolhas repetidas diariamente. O Vida Forte existe para lembrar voce de que cada missao concluida fortalece seu corpo, sua mente e seu carater. Evoluir e uma decisao diaria.",
    aboutText: "Vida Forte e um aplicativo desenvolvido para ajudar voce a construir habitos saudaveis e evoluir continuamente na saude fisica, mental e espiritual. Nossa missao e tornar o desenvolvimento pessoal simples, motivador e acessivel para todos.",
    missionText: "Transformar pequenas acoes diarias em grandes mudancas de vida.",
    noConnection: "Sem conexao com a internet. Seus dados estao salvos localmente.",
    serverError: "Erro no servidor. Tente novamente mais tarde.",
    dataSaved: "Dados salvos com sucesso!",
    deleteConfirm: "Tem certeza que deseja excluir? Esta acao nao pode ser desfeita.",
    backupCreated: "Backup criado com sucesso!",
    backupRestored: "Backup restaurado com sucesso!",
    male: "Masculino",
    female: "Feminino",
    other: "Outro",
    beginner: "Iniciante",
    discipline: "Disciplina",
    consistency: "Constancia",
    resilience: "Resiliencia",
    elite: "Elite",
    infinity: "Infinity",
  },
  en: {
    name: "English",
    welcome: "Welcome",
    habits: "Habits",
    stats: "Statistics",
    community: "Community",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    save: "Save",
    cancel: "Cancel",
    edit: "Edit",
    delete: "Delete",
    confirm: "Confirm",
    back: "Back",
    next: "Next",
    done: "Done",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    offline: "No connection",
    retry: "Retry",
    water: "Water",
    sleep: "Sleep",
    workout: "Workout",
    reading: "Reading",
    meditation: "Meditation",
    nutrition: "Nutrition",
    streak: "Streak",
    level: "Level",
    xp: "XP",
    dailyMission: "Daily Mission",
    coach: "Dr. Helena",
    manifesto: "Vida Forte Manifesto",
    about: "About",
    privacy: "Privacy",
    terms: "Terms of Use",
    support: "Support",
    share: "Share",
    rate: "Rate",
    suggest: "Send suggestion",
    report: "Report issue",
    contact: "Contact us",
    version: "Version",
    changelog: "Changelog",
    thankYou: "Thank you for being part of VIDA FORTE. Every completed habit is a step toward your best version. Keep evolving.",
    manifestoText: "We believe great transformations don't happen in a single day. They are built by small choices repeated daily. Vida Forte exists to remind you that every completed mission strengthens your body, mind, and character. Evolving is a daily decision.",
    aboutText: "Vida Forte is an app developed to help you build healthy habits and continuously evolve in physical, mental, and spiritual health. Our mission is to make personal development simple, motivating, and accessible to everyone.",
    missionText: "Transform small daily actions into big life changes.",
    noConnection: "No internet connection. Your data is saved locally.",
    serverError: "Server error. Please try again later.",
    dataSaved: "Data saved successfully!",
    deleteConfirm: "Are you sure you want to delete? This action cannot be undone.",
    backupCreated: "Backup created successfully!",
    backupRestored: "Backup restored successfully!",
    male: "Male",
    female: "Female",
    other: "Other",
    beginner: "Beginner",
    discipline: "Discipline",
    consistency: "Consistency",
    resilience: "Resilience",
    elite: "Elite",
    infinity: "Infinity",
  },
  es: {
    name: "Espanol",
    welcome: "Bienvenido",
    habits: "Habitos",
    stats: "Estadisticas",
    community: "Comunidad",
    profile: "Perfil",
    settings: "Configuracion",
    logout: "Cerrar sesion",
    save: "Guardar",
    cancel: "Cancelar",
    edit: "Editar",
    delete: "Eliminar",
    confirm: "Confirmar",
    back: "Atras",
    next: "Siguiente",
    done: "Hecho",
    loading: "Cargando...",
    error: "Error",
    success: "Exito",
    offline: "Sin conexion",
    retry: "Reintentar",
    water: "Agua",
    sleep: "Sueno",
    workout: "Entrenamiento",
    reading: "Lectura",
    meditation: "Meditacion",
    nutrition: "Nutricion",
    streak: "Racha",
    level: "Nivel",
    xp: "XP",
    dailyMission: "Mision Diaria",
    coach: "Dra. Helena",
    manifesto: "Manifiesto Vida Forte",
    about: "Acerca de",
    privacy: "Privacidad",
    terms: "Terminos de Uso",
    support: "Soporte",
    share: "Compartir",
    rate: "Calificar",
    suggest: "Enviar sugerencia",
    report: "Reportar problema",
    contact: "Contactanos",
    version: "Version",
    changelog: "Novedades",
    thankYou: "Gracias por ser parte de VIDA FORTE. Cada habito completado es un paso hacia tu mejor version. Sigue evolucionando.",
    manifestoText: "Creemos que las grandes transformaciones no ocurren en un solo dia. Se construyen con pequenas elecciones repetidas diariamente. Vida Forte existe para recordarte que cada mision completada fortalece tu cuerpo, mente y caracter. Evolucionar es una decision diaria.",
    aboutText: "Vida Forte es una aplicacion desarrollada para ayudarte a construir habitos saludables y evolucionar continuamente en salud fisica, mental y espiritual. Nuestra mision es hacer el desarrollo personal simple, motivador y accesible para todos.",
    missionText: "Transformar pequenas acciones diarias en grandes cambios de vida.",
    noConnection: "Sin conexion a internet. Tus datos estan guardados localmente.",
    serverError: "Error del servidor. Intentelo de nuevo mas tarde.",
    dataSaved: "Datos guardados con exito!",
    deleteConfirm: "Estas seguro de que deseas eliminar? Esta accion no se puede deshacer.",
    backupCreated: "Respaldo creado con exito!",
    backupRestored: "Respaldo restaurado con exito!",
    male: "Masculino",
    female: "Femenino",
    other: "Otro",
    beginner: "Principiante",
    discipline: "Disciplina",
    consistency: "Constancia",
    resilience: "Resiliencia",
    elite: "Elite",
    infinity: "Infinity",
  }
};

const LEVEL_MAP = [
  { name: "beginner", label: "Iniciante", minXp: 0, color: "#8FA69A" },
  { name: "discipline", label: "Disciplina", minXp: 1000, color: "#39FF6A" },
  { name: "consistency", label: "Constancia", minXp: 5000, color: "#22C55E" },
  { name: "resilience", label: "Resiliencia", minXp: 15000, color: "#16A34A" },
  { name: "elite", label: "Elite", minXp: 40000, color: "#15803D" },
  { name: "infinity", label: "Infinity", minXp: 100000, color: "#39FF6A" },
];

const ACHIEVEMENTS = [
  { id: "first_habit", title: "Primeiro Passo", desc: "Complete seu primeiro habito", icon: "CheckCircle2", xp: 50 },
  { id: "week_streak", title: "7 Dias", desc: "Mantenha uma sequencia de 7 dias", icon: "Flame", xp: 200 },
  { id: "month_streak", title: "30 Dias", desc: "Mantenha uma sequencia de 30 dias", icon: "Trophy", xp: 500 },
  { id: "century_streak", title: "100 Dias", desc: "Mantenha uma sequencia de 100 dias", icon: "Award", xp: 2000 },
  { id: "water_master", title: "Mestre da Agua", desc: "Complete agua por 30 dias seguidos", icon: "Droplet", xp: 300 },
  { id: "workout_warrior", title: "Guerreiro", desc: "Complete 50 treinos", icon: "Dumbbell", xp: 1000 },
  { id: "bookworm", title: "Leitor", desc: "Complete leitura por 30 dias", icon: "BookOpen", xp: 400 },
  { id: "perfectionist", title: "Perfeccionista", desc: "Complete todos os habitos em um dia", icon: "Star", xp: 500 },
  { id: "level_10", title: "Nivel 10", desc: "Alcance o nivel 10", icon: "TrendingUp", xp: 0 },
  { id: "level_25", title: "Nivel 25", desc: "Alcance o nivel 25", icon: "Zap", xp: 0 },
  { id: "level_50", title: "Nivel 50", desc: "Alcance o nivel 50", icon: "Crown", xp: 0 },
];

const DEFAULT_HABITS = [
  { id: "agua", label: "Agua", meta: "2L", xp: 20, icon: "Droplet", done: false, streak: 0, bestStreak: 0, history: [] },
  { id: "treino", label: "Treino", meta: "30 min", xp: 100, icon: "Dumbbell", done: false, streak: 0, bestStreak: 0, history: [] },
  { id: "alimentacao", label: "Alimentacao", meta: "3 refeicoes", xp: 60, icon: "Utensils", done: false, streak: 0, bestStreak: 0, history: [] },
  { id: "leitura", label: "Leitura", meta: "10 paginas", xp: 40, icon: "BookOpen", done: false, streak: 0, bestStreak: 0, history: [] },
  { id: "sono", label: "Sono", meta: "7h30", xp: 30, icon: "Moon", done: false, streak: 0, bestStreak: 0, history: [] },
  { id: "meditacao", label: "Meditacao", meta: "10 min", xp: 30, icon: "Brain", done: false, streak: 0, bestStreak: 0, history: [] },
];

const DEFAULT_MEALS = [
  { id: "cafe", title: "Cafe da manha", time: "07:30", kcal: 420, done: false, items: ["2 ovos mexidos", "Aveia com banana", "Cafe sem acucar"] },
  { id: "almoco", title: "Almoco", time: "12:30", kcal: 610, done: false, items: ["Frango grelhado", "Arroz integral", "Salada com azeite"] },
  { id: "lanche", title: "Lanche da tarde", time: "16:00", kcal: 210, done: false, items: ["Iogurte natural", "Mix de castanhas"] },
  { id: "jantar", title: "Jantar", time: "20:00", kcal: 480, done: false, items: ["Salmao assado", "Legumes no vapor", "Quinoa"] },
];

const DEFAULT_SETTINGS = {
  language: "pt",
  darkMode: true,
  animations: true,
  sound: true,
  vibration: true,
  showXpBar: true,
  showProgressPercent: true,
  coachMode: "texto",
  coachVoice: "female",
  coachFrequency: "medium",
  motivationalMessages: true,
  greetingOnOpen: true,
  coachPersonality: "balanced",
  notifications: {
    water: true,
    workout: true,
    reading: true,
    sleep: true,
    custom: [],
    silent: false,
  },
  showRanking: true,
  showStreak: true,
  showAchievements: true,
  confettiOnLevelUp: true,
  ambientMusic: false,
  effectVolume: 0.7,
  focusMusic: false,
  biometricLock: false,
  pinLock: false,
  pin: null,
  autoBackup: true,
};

const DEFAULT_USER = {
  name: "",
  email: "",
  avatar: null,
  age: null,
  gender: "",
  height: null,
  weight: null,
  goal: "",
  registeredAt: null,
  lastLogin: null,
};

export default App;